### ISSUE TITLE
[UserStory] Compare Common-Use Automated Build Tools Suitable for the Project

### ISSUE THREAD

**Issue by MaTTerCuBe** [MetroCS/QualityToolsForBlueJ#17]
# User Story
### Essential components
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a developer
I want  to know which build tool is most suitable for this project
so that  I can establish a build-environment as requested by User-Story #2 

## Acceptance Criteria
Rules or scenarios are acceptable formats.

* A Report must exist in Repository
* Report must specify why compared build-tools were chosen
* Report must include unique and relevant features of each compared tool
* Report must include Developer reviews or responses of compared tools
* Report must cite sources

~~**Scenario 1**
Given  that no Build Environment has been established yet
when  the project has access to a comparison of suitable build tools
then  a decision can be made about which build tool to use in order to establish a build-environment~~
