### ISSUE TITLE
[UserStory]integrate checkstyle and spotbugs into a bluej extension

### ISSUE THREAD

**Issue by JustinSingleton303** [MetroCS/QualityToolsForBlueJ#33]
# User Story
### Essential components
[x] Title describes the story
[x] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

Story
As a developer. 
I want a clearly defined process for integrating the checkstyle and spotbugs tools into the extension. 
so that we can successfully create a wrapper class for each tool so they can be utilized through the use of the BlueJ IDE 

### Scenario 1

When we can successfully run spotbugs and checkstyle while in the BlueJ ide, without it feeling like we are using other software.  

## Supporting Information
_(Relevant information, context, resources)_

## Dependencies
Depends On
Having an approved build environment
https://github.com/MetroCS/QualityToolsForBlueJ/issues/2

### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
Inactive.
